/// <reference types="@sveltejs/kit" />
import { build, files, version } from '$service-worker';

const CACHE = `cache-${version}`;

// Static files generated by Vite and files from the static folder
const ASSETS = [
  ...build,
  ...files,
  '/',
  '/index.html'
];

self.addEventListener('install', (event) => {
  async function addFilesToCache() {
    const cache = await caches.open(CACHE);
    // Cache files individually to prevent 404 errors from breaking the installation
    for (const asset of ASSETS) {
      try {
        await cache.add(asset);
      } catch (err) {
        console.warn(`[Service Worker] Failed to pre-cache: ${asset}`, err);
      }
    }
  }

  event.waitUntil(addFilesToCache());
});

self.addEventListener('activate', (event) => {
  async function deleteOldCaches() {
    for (const key of await caches.keys()) {
      if (key !== CACHE) {
        await caches.delete(key);
      }
    }
  }

  event.waitUntil(deleteOldCaches());
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;

  async function respond() {
    const url = new URL(event.request.url);
    const cache = await caches.open(CACHE);

    // 1. Static resources (generated or static SvelteKit assets) -> Cache-First
    const isStaticAsset = ASSETS.includes(url.pathname) || url.pathname.startsWith('/_app/');

    if (isStaticAsset) {
      const cached = await cache.match(event.request);
      if (cached) return cached;
    }

    // 2. Dynamic requests (API, page navigations, etc.) -> Network-First with Cache fallback
    try {
      const response = await fetch(event.request);
      
      const isHttp = url.protocol.startsWith('http');
      // We only store in cache if the response is successful (status 200)
      if (isHttp && response.status === 200) {
        cache.put(event.request, response.clone());
      }
      
      return response;
    } catch (err) {
      // Offline fallback: try to retrieve from cache
      const cached = await cache.match(event.request);
      if (cached) return cached;

      // If it fails and it is a page navigation, return index.html from cache
      if (event.request.mode === 'navigate') {
        const fallback = await cache.match('/index.html') || await cache.match('/');
        if (fallback) return fallback;
      }
      
      throw err;
    }
  }

  event.respondWith(respond());
});
